# -*- coding: utf-8 -*-
"""Harin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19j5PG-sS3ioVs1YFBTLAoZ3UBX8Y0R1H
"""

import csv
import string
import numpy
import matplotlib.pyplot as pt
from scipy.integrate import quad

T_solid = []
c_p_solid = []

T_liquid = []
c_p_liquid = []

T_gas = []
c_p_gas = []

from google.colab import files
uploaded = files.upload()

with open("naphthalene_heat_capacity.csv", "r") as csvfile:

    reader_variable = csv.reader(csvfile, delimiter=",")
    next(reader_variable, None)
    for row in reader_variable:
        if row[2] == 'S':
            T_solid.append(float(row[0]))
            c_p_solid.append(float(row[1]))
        elif row[2] == 'L':
            T_liquid.append(float(row[0]))
            c_p_liquid.append(float(row[1]))
        elif row[2] == 'G':
            T_gas.append(float(row[0]))
            c_p_gas.append(float(row[1]))

print(T_solid)
print(c_p_solid)

print(T_liquid)
print(c_p_liquid)

print(T_gas)
print(c_p_gas)


T_ref = 298.15 #K

# I assumed that c_p value is linearly dependent on the temperature.
# from given set of c_p and temperature I found a linear equation from https://www.dcode.fr/function-equation-finder
# c_p as function for gas phase c_p(T) = 0.24*T + 102.6
# d(H) = c_p*d(T) ==> d(S) = d(H)/T ==> d(S) = c_p*d(T)/T
#It is further assume that entropy is only function of temperature ==> During phase change entropy remain constant.

def S(T):                              #entropy function

    return 0.24 + (102.6*T**-1)

def int(T):                            #integration of entropy function to get numerical value of entropy

    intg, _ = quad(S, T_ref, T)
    return intg

Temp = numpy.linspace(T_ref, 1500, 100) #K

ent_value = [int(T) for T in Temp]     #J/mol


print(ent_value)
print(Temp)

pt.scatter(Temp, ent_value,)
pt.title('Entropy of naphthalene')
pt.xlabel('Temperature, K')
pt.ylabel('S(T) - S(0), J/mol')

# OVERALL GRADE: 0 + 0 + 0 = 0

# 1. read phase change data from a separate csv file: 0 from 2
# 2. find a way how to handle temperature-dependent heat capacity of the gas phase: 0 from 4
# 3. calculate entropy of naphthalene as a function of temperature: 0 from 4